default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: 127.0.0.1
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: data_development

test:
  <<: *default
  database: data_test

production:
  <<: *default
  database: data_production
  username: data-backend
  password:
